#theme: minima
#remote_theme: "mmistakes/minimal-mistakes@4.24.0"

plugins:
  - jekyll-github-metadata
  - jekyll-include-cache

theme: minima

title: Some Thoughts
description: A collection of different tidbits about interesting topics I encountered

header_pages:
  - projects.md
  - posts.md